version: '3.8'

services:
  db:
    networks:
      - network_onlineShop
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5434:5432"
    expose:
      - "5432"

  shop-app:
    build:
      context: ./shop-app
    networks:
      - network_onlineShop
    ports:
      - "8888:8888"
    env_file:
      - .env
    depends_on:
      - db
      - payments-app
    environment:
      - PAYMENTS_URL=http://payments-app:8082


  payments-app:
    build:
      context: ./payments-app
    networks:
      - network_onlineShop
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      - db


networks:
  network_onlineShop:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
