version: '3.8'

services:
  db:
    networks:
      - network_onlineShop
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5434:5432"
    expose:
      - "5432"

  app:
    build: .
    networks:
      - network_onlineShop
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db


networks:
  network_onlineShop:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
