<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<!-- оставляем как у тебя -->
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.0</version>
		<relativePath/>
	</parent>

	<groupId>kz.timshowtime</groupId>
	<artifactId>onlineShop</artifactId>
	<version>0.0.6-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>onlineShop</name>
	<properties>
		<java.version>21</java.version>
		<openapi.generator.version>7.5.0</openapi.generator.version>
<!--		<spec.path>C:/Practicum/onlineShop/payments-spec/src/main/resources/openapi/payments.yaml</spec.path>-->
	</properties>

	<modules>
		<module>payments-spec</module>
		<module>payments-app</module>
		<module>shop-app</module>
	</modules>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
