spring.application.name=payments-app
server.port=8082
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.reactive.function.server=DEBUG

account.balance=5000000.0
spring.jackson.default-property-inclusion=non_null

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/onlineshop
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/onlineshop/protocol/openid-connect/certs

spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/paymentservice}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:postgres}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:12345}

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/master/db.payments-changelog-master.xml
spring.liquibase.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paymentservice}
spring.liquibase.user=${SPRING_DATASOURCE_USERNAME:postgres}
spring.liquibase.password=${SPRING_DATASOURCE_PASSWORD:12345}