create table if not exists cart
(
    id          integer generated by default as identity
        primary key,
    total_price integer
);

create table if not exists cart_items
(
    cart_id   integer not null
        constraint fk_cart_items_cart
            references cart,
    item_id   integer not null
        constraint fk_cart_items_item
            references item,
    quantity  integer not null,
    create_dt timestamp default now()
);

create table if not exists item
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(256),
    price       integer,
    preview     bytea,
    description text
);

create table orders
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(60),
    total_price integer,
    create_dt   timestamp default now()
);

create table orders_items
(
    order_id bigint  not null
        constraint fk_order_items_order
            references orders,
    item_id  bigint  not null
        constraint fk_orders_items_item
            references item,
    quantity integer not null
);