<!-- onlineShop/payments-app/pom.xml -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>kz.timshowtime</groupId>
        <artifactId>onlineShop</artifactId>
        <version>0.0.6-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>payments-app</artifactId>
    <name>payments-app</name>
    <packaging>jar</packaging>

    <dependencies>
        <!-- выбрал WebFlux, чтобы соответствовать вашему стеку -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>

        <!-- Lombok по желанию -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.38</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- (опционально, если будешь юзать StepVerifier) -->
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>kz.timshowtime</groupId>
            <artifactId>payments-spec</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>2.2.21</version>
        </dependency>

        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>3.0.2</version>
        </dependency>

        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.6</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>kz.timshowtime.paymentsapp.PaymentsAppApplication</mainClass>
                    <classifier>exec</classifier>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- B) ГЕНЕРАЦИЯ СЕРВЕРНЫХ ЗАГЛУШЕК -->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi.generator.version}</version>
                <executions>
                    <execution>
                        <id>generate-spring-server</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <!-- Путь до YAML -->
<!--                            <inputSpec>${basedir}/../payments-spec/src/main/resources/openapi/payments.yaml</inputSpec>-->

                             <inputSpec>../payments-spec/src/main/resources/openapi/payments.yaml</inputSpec>
                            <generatorName>spring</generatorName>

                            <output>${project.build.directory}/generated-sources/openapi</output>
                            <apiPackage>kz.timshowtime.paymentsapp.gen.api</apiPackage>
                            <modelPackage>kz.timshowtime.paymentsapp.gen.model</modelPackage>
                            <addCompileSourceRoot>true</addCompileSourceRoot>


                            <configOptions>
                                <useSpringBoot3>true</useSpringBoot3>
                                <reactive>true</reactive>
                                <useJakartaEe>true</useJakartaEe>
                                <useBeanValidation>true</useBeanValidation>
                                <delegatePattern>true</delegatePattern>
                                <useTags>true</useTags>
                            </configOptions>

                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>

                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>
