spring:
  # JDBC for Liquibase
  r2dbc:
    url: ${SPRING_DATASOURCE_URL:r2dbc:postgresql://localhost:5432/onlineshop}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}

  liquibase:
    enabled: true
    change-log: classpath:db/master/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/onlineshop
    user: postgres
    password: 12345

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 8888


logging:
  level:
    liquibase: debug
    org.springframework.web: DEBUG
    org.springframework.web.reactive.function.server: DEBUG