spring:
  # JDBC for Liquibase
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/onlineshop}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:12345}

  liquibase:
    enabled: true
    change-log: classpath:db/master/db.changelog-master.xml
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/onlineshop}
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 8888

payments:
  url: ${PAYMENTS_URL:http://localhost:8082}


logging:
  level:
    liquibase: debug
    org.springframework.web: DEBUG
    org.springframework.web.reactive.function.server: DEBUG