create table if not exists users
(
    id         bigserial primary key,
    username   varchar(100) not null unique,
    password   varchar(255) not null,
    role       varchar(50)  not null,
    created_at timestamp with time zone default now()
);

create table if not exists item
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(256),
    price       integer,
    preview     bytea,
    description text
);

create table if not exists cart
(
    id          integer generated by default as identity
        primary key,
    total_price integer,
    user_id     bigint
        constraint fk_cart_user references users
);

create table if not exists cart_items
(
    id bigint generated by default as identity primary key,
    cart_id   integer not null
        constraint fk_cart_items_cart
            references cart,
    item_id   integer not null
        constraint fk_cart_items_item
            references item,
    quantity  integer not null,
    create_dt timestamp default now()
);

create table if not exists orders
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(60),
    total_price integer,
    create_dt   timestamp default now(),
    user_id     bigint
        constraint fk_orders_users references users
);

create table if not exists orders_items
(
    id          bigint generated by default as identity
        primary key,
    order_id bigint  not null
        constraint fk_order_items_order
            references orders,
    item_id  bigint  not null
        constraint fk_orders_items_item
            references item,
    quantity integer not null
);
